{{- if and .Values.traefik.enabled .Values.traefik.middlewares.securityHeaders -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "tiskit.fullname" . }}-security-headers
  labels: {{- include "tiskit.labels" . | nindent 4 }}
spec:
  headers:
    stsSeconds: 63072000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
    contentTypeNosniff: true
    frameDeny: true
    browserXssFilter: true
    referrerPolicy: no-referrer
    permissionsPolicy: "geolocation=(), microphone=(), camera=(), payment=()"
    contentSecurityPolicy: "default-src 'self'; style-src 'self'; script-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'"
    customResponseHeaders:
      X-Robots-Tag: "noindex, nofollow"
      Cache-Control: "no-store, no-cache, must-revalidate, max-age=0, private"
      Pragma: "no-cache"
      Server: ""
{{- end }}
